import React from 'react';
import Layout from './home/layout/Layout';
import Slider2 from './home/slider/Slider2';
import CTA from './CTA';
import SentCounter from './SentCounter';
import Slider1 from './home/slider/Slider1';

const Home = (props) => {

	return (
		<Layout>
			<section className="xl:bg-[length:100vw_auto] bg-top bg-no-repeat -mt-24 pt-24" style={{ backgroundImage: "url('assets/imgs/backgrounds/intersect.svg')" }}>
				<div className="hidden lg:block absolute inset-0 w-1/2 ml-auto bg-gray-100 z-0" style={{ "zIndex": "-1" }}></div>
				<div className="container mx-auto">
					<div className="pt-12 text-center">
						<div className="max-w-2xl mx-auto mb-8">
							<h2 className="text-3xl lg:text-4xl lg:leading-normal mb-4 font-bold font-heading wow animate__animated animate__fadeIn">
								Send <span className="text-blue-500">cold</span> messages<br/>
								Establish <span className="text-orange-500">warm</span> relationships
							</h2>
							<div className="text-lg lg:text-2xl text-gray-700 leading-relaxed wow animate__animated animate__fadeIn d-inline">
								Unique Twitter DMs generated by AI based on your leads' profiles
							</div>
						</div>
					</div>
				</div>
			</section>

			<section className="mt-20 mx-10" id="swiper">
				<Slider1 />
			</section>

			<CTA/>

			<SentCounter/>


		</Layout>
	)


}

export default Home;
