import React from 'react';
import Layout from './home/layout/Layout';
import Slider2 from './home/slider/Slider2';
import CTA from './CTA';
import SentCounter from './SentCounter';
import Slider1 from './home/slider/Slider1';

const Home = (props) => {

	return (
		<Layout>
			<section className="xl:bg-[length:100vw_auto] bg-top bg-no-repeat -mt-24 pt-24">
				<div className="hidden lg:block absolute inset-0 w-1/2 ml-auto bg-gray-100 z-0" style={{ "zIndex": "-1" }}></div>
				<div className="container mx-auto">
					<div className="pt-12 text-center">
						<div className="max-w-2xl mx-auto mb-8">
							<h2 className="text-3xl lg:text-4xl lg:leading-normal mb-4 font-bold font-heading wow animate__animated animate__fadeIn">
								Send <span className="text-indigo-500">cold</span> messages<br/>
								Establish <span className="text-amber-600">warm</span> relationships
							</h2>
							<div className="text-lg lg:text-2xl text-gray-700 leading-relaxed wow animate__animated animate__fadeIn d-inline">
								Unique Twitter DMs generated by AI based on your leads' profiles
							</div>
						</div>
					</div>
				</div>
			</section>

			<section className="mt-20 mx-10" id="swiper">
				<Slider1 />
			</section>

			<section className="mt-20 mx-auto max-w-screen-sm" id="finder">
				<div className="bg-slate-100 py-8 shadow rounded-sm">
					<h1 className="text-4xl font-bold text-center mb-4">Discover More Leads on Twitter with Our AI-powered Tool</h1>
					<div className="container mx-auto px-6">
						<p className="text-lg">🔎 By analyzing data from Twitter and using advanced algorithms, we can identify potential customers who may be interested in your products or services. </p>
						<p className="text-lg mt-4">🎯 With our tool, you can target these leads with precision, increasing the chances of converting them into paying customers. </p>
						<p className="text-lg mt-4">📈 Whether you're looking to grow your business or expand your customer base, our AI-powered tool can help you achieve your goals.</p>
					</div>
				</div>
			</section>			

			<CTA/>

			<SentCounter/>


		</Layout>
	)


}

export default Home;
